application: omiai-bot
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
- url: /task/.*
  script: main.py
  login: admin
- url: .*
  script: main.py
